version: '3.8'

services:
  app:
    image: api-node:1.0
    container_name: api-ads-labs-container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=API_ADS-LABS
      - DB_DIALECT=mysql
      - PORT=3000
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=API_ADS-LABS
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: